#!/usr/bin/env python
# Copyright (c) Paul Tagliamonte <paultag@debian.org> under the terms and
# conditions of the Expat license.

import sys
import json

from monomoy.builder import add_builder
from monomoy.utils import JSONEncoder
from pymongo.errors import DuplicateKeyError
from monomoy.db import db


if len(sys.argv) < 3:
    print "Need a JSON dump"
    sys.exit(1)

data = json.load(open(sys.argv[2], 'r'))

try:
    ret = add_builder(**data)
    obj = db.builders.find_one({ "_id": ret })
    print json.dumps({
        "success": obj
    }, cls=JSONEncoder)
except DuplicateKeyError:
    print json.dumps({
        "error": "builder is already in the db"
    })
