#!/usr/bin/env python
# Copyright (c) Paul Tagliamonte <paultag@debian.org> under the terms and
# conditions of the Expat license.

import sys
from monomoy.queue import close_job
from bson.objectid import ObjectId

if len(sys.argv) < 3:
    print "Need ID"
    sys.exit(1)

print close_job(ObjectId(sys.argv[2]))
