#!/usr/bin/env python
# Copyright (c) Paul Tagliamonte <paultag@debian.org> under the terms and
# conditions of the Expat license.

import sys
import json
from monomoy.queue import take_job
from monomoy.utils import JSONEncoder
from monomoy.mail import jinja_mail

if len(sys.argv) < 3:
    print "Need ID"
    sys.exit(1)

builder, job = take_job(sys.argv[2])

if builder is not None and job is not None:
    jinja_mail("Builder took a build.", "builder-take.mail", {
        "builder": builder,
        "job": job
    })

print json.dumps(job, cls=JSONEncoder)
