#!/usr/bin/env python
# Copyright (c) Paul Tagliamonte <paultag@debian.org> under the terms and
# conditions of the Expat license.

import sys
import json
from bson.objectid import ObjectId
from monomoy.queue import close_job
from monomoy.utils import JSONEncoder
from monomoy.mail import simple_mail

if len(sys.argv) < 3:
    print "Need ID"
    sys.exit(1)

obj = close_job(ObjectId(sys.argv[2]))

simple_mail("Job finished", """
Some random build finished.
""")

print json.dumps(obj, cls=JSONEncoder)
