#!/usr/bin/env python
# Copyright (c) Paul Tagliamonte <paultag@debian.org> under the terms and
# conditions of the Expat license.

import sys
import json
from monomoy.queue import next_job
from monomoy.utils import JSONEncoder

if len(sys.argv) < 3:
    print "Need ID"
    sys.exit(1)

print json.dumps(next_job(sys.argv[2]),
                 cls=JSONEncoder)
