#!/usr/bin/env python
# Copyright (c) Paul Tagliamonte <paultag@debian.org> under the terms and
# conditions of the Expat license.

import sys
from monomoy.builder import ping_from_builder

if len(sys.argv) < 3:
    print "Need ID"
    sys.exit(1)

results = ping_from_builder(sys.argv[2])

if results['n'] == 0:
    print "Looks like you're not set up for monomoy. Register the builder."
    sys.exit(2)

print "Heartbeat ACK'd."
