#!/usr/bin/env python
# Copyright (c) Paul Tagliamonte <paultag@debian.org> under the terms and
# conditions of the Expat license.

import sys
import json

from monomoy.incoming import get_path

if len(sys.argv) < 3:
    print "Need ID"
    sys.exit(1)

print get_path("", sys.argv[2])
