#!/usr/bin/env python
# Copyright (c) Paul Tagliamonte <paultag@debian.org> under the terms and
# conditions of the Expat license.

import sys
import json
from monomoy.queue import garbage_collect

if len(sys.argv) < 3:
    print "Need the JSON settings file"
    sys.exit(1)
obj = json.load(open(sys.argv[2], 'r'))

exp = obj['build_expired_time']
tout = obj['builder_timeout']

garbage_collect(exp, tout)
