#!/usr/bin/env python
# Copyright (c) Paul Tagliamonte <paultag@debian.org> under the terms and
# conditions of the Expat license.

import sys
import json

if len(sys.argv) < 3:
    print "Need the JSON settings file"
    sys.exit(1)

key = sys.argv[3]
obj = json.load(open(sys.argv[2], 'r'))

if key in obj:
    print json.dumps(obj[key])
else:
    print json.dumps(None)
