#!/usr/bin/env python
# Copyright (c) Paul Tagliamonte <paultag@debian.org> under the terms and
# conditions of the Expat license.

from monomoy.db import db

db.changes.drop()
db.controls.drop()
db.jobs.drop()
db.builds.drop()
