#!/usr/bin/env python
# Copyright (c) Paul Tagliamonte <paultag@debian.org> under the terms and
# conditions of the Expat license.

import json
import sys

from monomoy.utils import parse_changes

if len(sys.argv) < 3:
    print "Give me a file!"
    sys.exit(1)

print json.dumps(parse_changes(sys.argv[2]), indent=4, sort_keys=True)
