#!/usr/bin/env python
# Copyright (c) Paul Tagliamonte <paultag@debian.org> under the terms and
# conditions of the Expat license.

from monomoy.incoming import process_incoming
from monomoy.mail import jinja_mail

import sys
import json
if len(sys.argv) < 3:
    print "Need the JSON settings file"
    sys.exit(1)
obj = json.load(open(sys.argv[2], 'r'))

incoming = obj['incoming']
pool = obj['pool']

accepted, rejected = process_incoming(incoming, pool, obj)

for package in accepted:
    jinja_mail("Accepted: %s" % (package), "accepted.mail", {
        "package": package
    })

for package in rejected:
    jinja_mail("Rejected: %s" % (package), "rejected.mail", {
        "package": package
    })
