#!/usr/bin/env python
# Copyright (c) Paul Tagliamonte <paultag@debian.org> under the terms and
# conditions of the Expat license.

from monomoy.incoming import process_incoming

import sys
import json
if len(sys.argv) < 3:
    print "Need the JSON settings file"
    sys.exit(1)
obj = json.load(open(sys.argv[2], 'r'))

incoming = obj['incoming']
pool = obj['pool']

process_incoming(incoming, pool, obj)
