#!/usr/bin/env python
# Copyright (c) Paul Tagliamonte <paultag@debian.org> under the terms and
# conditions of the Expat license.

import os
import sys
import json

from monomoy.db import db
from bson.objectid import ObjectId

if len(sys.argv) < 3:
    print "Need the report"
    sys.exit(1)

obj = json.load(open(sys.argv[2], 'r'))
jraw = obj['build']
job = ObjectId(jraw)
del(obj['build'])

build = db.builds.find_one({"_id": job})

if build is None:
    print "Erm, crap. Bad build ID: %s" % (job)
    sys.exit(2)

build['report'] = obj

db.builds.update({"_id": job},
                build,
                False,
                safe=True)
